package ch.desm.middleware.app.core.component;

import ch.desm.middleware.app.core.component.ComponentMapBase;

import java.util.Map;

public class ComponentMapMiddleware extends ComponentMapBase {

	@Override
	public Map<String, String> getMap() {
		return map;
	}
	
	@Override
	protected void initialize(){
        map.put("1.90.01", "1.90.01;;0;lampe;signalfstern;gestört;?;stellwerkobermattlangnau;#");	map.put("w1_endlage_plus", "w1_endlage_plus;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.113", "locsim.dll.signal.113;os;0;signal;blocksignauemmenmattdoppelspur–einspur;p832;?;locsim-dll;#");	map.put("s126.1", "s126.1;;0;schalter;haupthahn;1;?;kabinere420;#");	map.put("mgmt.stellwerk.obermattlangnau", "mgmt.stellwerk.obermattlangnau;os;0;management;stellwerk;obermattlangnau;?;management;#");
        map.put("1.90.02", "1.90.02;o;0;lampe;signalf;notrot;?;stellwerkobermattlangnau;#");	map.put("w1_endlage_minus", "w1_endlage_minus;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.114", "locsim.dll.signal.114;os;0;signal;zwergdoppelspur–einspur;zwerg43;?;locsim-dll;#");	map.put("s126", "s126;i;0;schalter;steuerstrom;0;?;kabinere420;#");	map.put("mgmt.petrinet.obermatlangnau", "mgmt.petrinet.obermatlangnau;os;0;management;petrinet;obermattlangnau;?;management;#");
        map.put("1.90.03", "1.90.03;o;0;lampe;signalf;grün_fb3;?;stellwerkobermattlangnau;#");	map.put("w1_gestoert_p", "w1_gestoert_p;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.115", "locsim.dll.signal.115;os;0;signal;einfahrvorsignalemmenmatt;astern833;?;locsim-dll;#");	map.put("s129", "s129;i;0;schalter;stromabnehmer;0;?;kabinere420;#");	map.put("mgmt.cabine.re420.fabisch", "mgmt.cabine.re420.fabisch;os;0;management;cabine;re420.fabisch;?;management;#");
        map.put("1.90.04", "1.90.04;o;0;lampe;signalf;rot;?;stellwerkobermattlangnau;#");	map.put("w1_gestoert_m", "w1_gestoert_m;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.116", "locsim.dll.signal.116;os;0;signal;geschwindigkeitsanzeige;vmaxastern833;?;locsim-dll;#");	map.put("s132", "s132;i;0;schalter;haupt;0;?;kabinere420;#");	map.put("mgmt.cabine.re420.ubw32", "mgmt.cabine.re420.ubw32;os;0;management;cabine;re420.ubw32;?;management;#");
        map.put("1.90.05", "1.90.05;o;0;lampe;signalf;grün_fb1;?;stellwerkobermattlangnau;#");	map.put("w1_keine_endlage", "w1_keine_endlage;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.117", "locsim.dll.signal.117;os;0;signal;einfahrsignalemmenmatt;a833;?;locsim-dll;#");	map.put("s172.1", "s172.1;i;0;schalter;kompressor;a;?;kabinere420;#");	map.put("mgmt.simulation.locsim.rs232", "mgmt.simulation.locsim.rs232;os;0;management;simulation;locsim.rs232;?;management;#");
        map.put("1.90.06", "1.90.06;o;0;lampe;signale;grün_fb1;?;stellwerkobermattlangnau;#");	map.put("fstr_ef_stoerung_e", "fstr_ef_stoerung_e;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.118", "locsim.dll.signal.118;os;0;signal;geschwindigkeitsanzeige;vmaxa833;?;locsim-dll;#");	map.put("s172.2", "s172.2;i;0;schalter;kompressor;d;?;kabinere420;#");	map.put("mgmt.simulation.locsim.dll", "mgmt.simulation.locsim.dll;os;0;management;simulation;locsim.dll;?;management;#");
        map.put("1.90.07", "1.90.07;o;0;lampe;signale;rot;?;stellwerkobermattlangnau;#");	map.put("fstr_ef_verschlossen", "fstr_ef_verschlossen;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.119", "locsim.dll.signal.119;os;0;signal;zwerg;zwerg44;?;locsim-dll;#");	map.put("s169", "s169;i;0;schalter;zugsammelschiene;0;?;kabinere420;#");
        map.put("1.90.08", "1.90.08;o;0;lampe;signale;notrot;?;stellwerkobermattlangnau;#");	map.put("emm_c_fahrt", "emm_c_fahrt;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.120", "locsim.dll.signal.120;os;0;signal;ausfahrsignalemmenmattgleis2;c2;?;locsim-dll;#");	map.put("s311", "s311;i;0;schalter;zug;0;?;kabinere420;#");
        map.put("1.90.09", "1.90.09;o;0;lampe;signalg;grün_fb1;?;stellwerkobermattlangnau;#");	map.put("emm_c_halt", "emm_c_halt;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.121", "locsim.dll.signal.121;os;0;signal;geschwindigkeitsanzeige;vmaxc2;?;locsim-dll;#");	map.put("s316_1", "s316_1;i;0;schalter;dienstbel;1;?;kabinere420;#");
        map.put("1.90.10", "1.90.10;o;0;lampe;signalg;rot;?;stellwerkobermattlangnau;#");	map.put("emm_c_fb1", "emm_c_fb1;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.122", "locsim.dll.signal.122;os;0;signal;zwerggleis2;zwerg45;?;locsim-dll;#");	map.put("s316_2", "s316_2;;0;schalter;dienstbel;2;?;kabinere420;#");
        map.put("1.90.11", "1.90.11;o;0;lampe;signalg;grün_fb3;?;stellwerkobermattlangnau;#");	map.put("emm_d_fb2", "emm_d_fb2;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.123", "locsim.dll.signal.123;os;0;signal;ausfahrsignalemmenmattgleis1;c1;?;locsim-dll;#");	map.put("s140a", "s140a;i;0;schalter;wende;vorwärts;?;kabinere420;#");
        map.put("1.90.12", "1.90.12;o;0;lampe;signald;rot;?;stellwerkobermattlangnau;#");	map.put("emm_d_fahrt", "emm_d_fahrt;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.124", "locsim.dll.signal.124;os;0;signal;zwerggleis1;zwerg46;?;locsim-dll;#");	map.put("s140b", "s140b;i;0;schalter;wende;rückwärts;?;kabinere420;#");
        map.put("1.90.13", "1.90.13;o;0;lampe;signald;grün;?;stellwerkobermattlangnau;#");	map.put("emm_d_halt", "emm_d_halt;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.125", "locsim.dll.signal.125;os;0;signal;einfahrsignalobermatt;a834;?;locsim-dll;#");	map.put("fahrschalter.bremsen.plus", "fahrschalter.bremsen.plus;i;0;fahrschalter;bremse;plus;?;kabinere420;#");
        map.put("1.90.14", "1.90.14;o;0;lampe;signalc;grün;?;stellwerkobermattlangnau;#");	map.put("emm_d_fb1", "emm_d_fb1;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.126", "locsim.dll.signal.126;os;0;signal;zwergobermatt;zwerg47;?;locsim-dll;#");	map.put("fahrschalter.bremsen.punkt", "fahrschalter.bremsen.punkt;i;0;fahrschalter;bremse;punkt;?;kabinere420;#");
        map.put("1.90.15", "1.90.15;o;0;lampe;signalc;rot;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft1a5", "ln_geprueft1a5;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.127", "locsim.dll.signal.127;os;0;signal;blocksignalp835;p835;?;locsim-dll;#");	map.put("fahrschalter.bremsen.minus", "fahrschalter.bremsen.minus;i;0;fahrschalter;bremse;minus;?;kabinere420;#");
        map.put("1.90.16", "1.90.16;o;0;lampe;signalgstern;gestört;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w1_pa3", "ln_ln_w1_pa3;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.128", "locsim.dll.signal.128;os;0;signal;blocksignalp;p837;?;locsim-dll;#");	map.put("fahrschalter.neutral", "fahrschalter.neutral;i;0;fahrschalter;neutral;;?;kabinere420;#");
        map.put("1.91.21", "1.91.21;o;0;lampe;fbv;von_zb;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft1a2", "ln_geprueft1a2;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.129", "locsim.dll.signal.129;os;0;signal;einfahrvorsignallangnau;p838;?;locsim-dll;#");	map.put("fahrschalter.fahren.minus", "fahrschalter.fahren.minus;i;0;fahrschalter;fahren;minus;?;kabinere420;#");
        map.put("1.91.22", "1.91.22;o;0;lampe;rm_möglich;nach_zb;?;stellwerkobermattlangnau;#");	map.put("ln_emm_grundstlg", "ln_emm_grundstlg;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.130", "locsim.dll.signal.130;os;0;signal;geschwindigkeitsanzeige;vmax838;?;locsim-dll;#");	map.put("fahrschalter.fahren.punkt", "fahrschalter.fahren.punkt;i;0;fahrschalter;fahren;punkt;?;kabinere420;#");
        map.put("1.90.31", "1.90.31;o;0;lampe;block_rot;von_ln;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft2a3", "ln_geprueft2a3;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.131", "locsim.dll.signal.131;os;0;signal;einfahrsignallangnau;a840;?;locsim-dll;#");	map.put("fahrschalter.fahren.m", "fahrschalter.fahren.m;i;0;fahrschalter;fahren;m;?;kabinere420;#");
        map.put("1.90.32", "1.90.32;o;0;lampe;block_weiss;von_ln;?;stellwerkobermattlangnau;#");	map.put("ln_ce_belegt", "ln_ce_belegt;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.132", "locsim.dll.signal.132;os;0;signal;geschwindigkeitsanzeige;vmax840;?;locsim-dll;#");	map.put("fahrschalter.fahren.plus", "fahrschalter.fahren.plus;i;0;fahrschalter;fahren;plus;?;kabinere420;#");
        map.put("1.90.33", "1.90.33;o;0;lampe;block_weiss;nach_ln;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft1e5", "ln_geprueft1e5;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.signal.133", "locsim.dll.signal.133;os;0;signal;zwergeinfahrweichelangnau;zwerg48;?;locsim-dll;#");	map.put("fahrschalter.fahren.plusplus", "fahrschalter.fahren.plusplus;i;0;fahrschalter;fahren;plusplus;?;kabinere420;#");
        map.put("1.90.34", "1.90.34;o;0;lampe;block_rot;nach_ln;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft1a4", "ln_geprueft1a4;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.weiche.emm10", "locsim.dll.weiche.emm10;os;0;einfache weiche;emm-1-2;emm-10;?;locsim-dll;#");	map.put("s189.1", "s189.1;i;0;schalter;pfeife;stufe1;?;kabinere420;#");
        map.put("1.90.35", "1.90.35;o;0;lampe;isolierung;egf;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w1_ma1", "ln_ln_w1_ma1;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.weiche.om1", "locsim.dll.weiche.om1;os;0;einfache weiche;om-833-138;om-1;?;locsim-dll;#");	map.put("s189.2", "s189.2;i;0;schalter;pfeife;stufe2;?;kabinere420;#");
        map.put("1.90.36", "1.90.36;o;0;lampe;isolierung;1;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft1e2", "ln_geprueft1e2;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.track.xyz", "locsim.dll.track.xyz;os;0;;;;?;locsim-dll;#");	map.put("s242.01", "s242.01;i;0;schalter;zugsicherung;zurückstellen;?;kabinere420;#");
        map.put("1.90.37", "1.90.37;o;0;lampe;fahrstrasse;ef;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w2_ma3", "ln_ln_w2_ma3;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.track.xyz", "locsim.dll.track.xyz;os;0;;;;?;locsim-dll;#");	map.put("s242.03", "s242.03;i;0;schalter;zub;zurückstellen;?;kabinere420;#");
        map.put("1.90.38", "1.90.38;o;0;lampe;isolierung;ef;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft1a1", "ln_geprueft1a1;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.track.xyz", "locsim.dll.track.xyz;os;0;;;;?;locsim-dll;#");	map.put("s242.02", "s242.02;i;0;taste;zugsicherung;manöver;?;kabinere420;#");
        map.put("1.90.39", "1.90.39;o;0;lampe;isolierung;cd;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w1_pa2", "ln_ln_w1_pa2;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.track.xyz", "locsim.dll.track.xyz;os;0;;;;?;locsim-dll;#");	map.put("s174", "s174;;0;taste;ventillator;aus;?;kabinere420;#");
        map.put("1.90.40", "1.90.40;o;0;lampe;fahrstrasse;gf;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft1e4", "ln_geprueft1e4;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.track.xyz", "locsim.dll.track.xyz;os;0;;;;?;locsim-dll;#");	map.put("s276_1", "s276_1;;0;schalter;bremse;r;?;kabinere420;#");
        map.put("1.90.41", "1.90.41;o;0;lampe;block_rot;nach_zb;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft1a3", "ln_geprueft1a3;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.track.xyz", "locsim.dll.track.xyz;os;0;;;;?;locsim-dll;#");	map.put("s276_2", "s276_2;;0;schalter;bremse;p;?;kabinere420;#");
        map.put("1.90.42", "1.90.42;o;0;lampe;block_weiss;nach_zb;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft2a2", "ln_geprueft2a2;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.track.xyz", "locsim.dll.track.xyz;os;0;;;;?;locsim-dll;#");	map.put("s276_3", "s276_3;;0;schalter;bremse;g;?;kabinere420;#");
        map.put("1.90.43", "1.90.43;o;0;lampe;block_weiss;von_zb;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft1e3", "ln_geprueft1e3;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.dll.track.xyz", "locsim.dll.track.xyz;os;0;;;;?;locsim-dll;#");	map.put("s241", "s241;;0;hebel;bvhahn;0;?;kabinere420;#");
        map.put("1.90.44", "1.90.44;o;0;lampe;block_rot;von_zb;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft1e1", "ln_geprueft1e1;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.initialization.ready.ini1", "locsim.initialization.ready.ini1;os;0;message;initialisiation;ini1;?;locsim-rs232;#");	map.put("s281", "s281;i;0;taste;schleuderschutz;0;?;kabinere420;#");
        map.put("1.91.01", "1.91.01;o;0;lampe;rm_möglich;nach_ln;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w2_pa2", "ln_ln_w2_pa2;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.initialization.ready.ini2", "locsim.initialization.ready.ini2;os;0;message;initialisiation;ini1;?;locsim-rs232;#");	map.put("s182.3", "s182.3;i;0;taste;türfreigabe;links;?;kabinere420;#");
        map.put("1.91.02", "1.91.02;o;0;lampe;fbv;von_ln;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft2a1", "ln_geprueft2a1;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.initialization.ready.ini1", "locsim.initialization.ready.ini1;os;0;message;initialisiation;ini1;?;locsim-rs232;#");	map.put("s182.4", "s182.4;i;0;taste;türfreigabe;rechts;?;kabinere420;#");
        map.put("1.91.03", "1.91.03;o;0;lampe;wecker;abschalten;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w3_pa3", "ln_ln_w3_pa3;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.auslöseschalter", "locsim.auslöseschalter;i;0;schalter;auslöse;;?;locsim-rs232;#");	map.put("s182", "s182;i;0;taste;türverriegelung;0;?;kabinere420;#");
        map.put("1.01.01", "1.01.01;o;0;lampe;ws1;freigabe;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w1_pa4", "ln_ln_w1_pa4;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.hauptleitungsdruck", "locsim.hauptleitungsdruck;o;0;;;;?;locsim-rs232;#");	map.put("s324.1", "s324.1;;0;schalter;fst;instrumente;?;kabinere420;#");
        map.put("1.01.02", "1.01.02;o;0;lampe;ws1;überwachung;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft2a4", "ln_geprueft2a4;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.rangierbremse", "locsim.rangierbremse;o;0;;;;?;locsim-rs232;#");	map.put("s324.2", "s324.2;;0;tastschalter;fst;fahrplan;?;kabinere420;#");
        map.put("2.92.01", "2.92.01;o;0;wecker;weichen;wecker;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w2_ma4", "ln_ln_w2_ma4;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.hldruck", "locsim.hldruck;o;0;analoganzeige;druck;hauptleitung;?;locsim-rs232;#");	map.put("s317", "s317;;0;tastschalter;fst;aufblend;?;kabinere420;#");
        map.put("2.92.02", "2.92.02;o;0;wecker;block;wecker;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w3_pa4", "ln_ln_w3_pa4;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.bremszylinderdruck", "locsim.bremszylinderdruck;o;0;analoganzeige;druck;bremszylinder;?;locsim-rs232;#");	map.put("s316.1", "s316.1;i;0;schalter;stirnlampe;linksweiss;?;kabinere420;#");
        map.put("2.90.01", "2.90.01;o;0;wecker;signale;wecker;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w5_pa3", "ln_ln_w5_pa3;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.fahrleitungsspannung", "locsim.fahrleitungsspannung;o;0;;;;?;locsim-rs232;#");	map.put("s316.4", "s316.4;i;0;schalter;stirnlampe;linksrot;?;kabinere420;#");
        map.put("9.99.04", "9.99.04;;1;sound;glocke;zug_von_emm;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w5_ma4", "ln_ln_w5_ma4;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.kompressorschalter.o", "locsim.kompressorschalter.o;i;0;schalter;kompressor;o;?;locsim-rs232;#");	map.put("s316.2", "s316.2;i;0;schalter;stirnlampe;obenweiss;?;kabinere420;#");
        map.put("9.99.05", "9.99.05;;1;sound;glocke;zug_von_ln;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w1_pa5", "ln_ln_w1_pa5;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.fahrtrichtungschalter.neutral", "locsim.fahrtrichtungschalter.neutral;i;0;schalter;fahrtrichtung;neutral;?;locsim-rs232;#");	map.put("s316.5", "s316.5;i;0;schalter;stirnlampe;obenrot;?;kabinere420;#");
        map.put("9.99.06", "9.99.06;;1;sound;glocke;zug_von_zb;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w3_ma5", "ln_ln_w3_ma5;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.hauptschalterschalter.hauptschalter.aus.kompressor.null", "locsim.hauptschalterschalter.hauptschalter.aus.kompressor.null;i;0;schalter;hauptschalter;aus;?;locsim-rs232;#");	map.put("s316.3", "s316.3;i;0;schalter;stirnlampe;rechtsweiss;?;kabinere420;#");
        map.put("9.99.07", "9.99.07;;1;sound;glocke;zug_nach_emm;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w2_ma5", "ln_ln_w2_ma5;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.wagentürenzustandinfo", "locsim.wagentürenzustandinfo;o;0;zustandinfo;tür;wagen;?;locsim-rs232;#");	map.put("s316.6", "s316.6;i;0;schalter;stirnlampe;rechtsrot;?;kabinere420;#");
        map.put("9.99.08", "9.99.08;;1;sound;glocke;zug_nach_ln;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w4_pa5", "ln_ln_w4_pa5;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.druckknopfsignalpfeife. aus", "locsim.druckknopfsignalpfeife. aus;o;0;druckknopf;pfeife;signal;?;locsim-rs232;#");	map.put("s324", "s324;;0;schalter;beleuchtung;führerstand;?;kabinere420;#");
        map.put("9.99.09", "9.99.09;;1;sound;glocke;zug_nach_zb;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft2a5", "ln_geprueft2a5;os;;;;;?;petrinetz-obermattlangnau;#");	map.put("locsim.schlüsselschalterabfertigungsbefehl", "locsim.schlüsselschalterabfertigungsbefehl;i;0;schalter;abfertigung;schlüssel;?;locsim-rs232;#");	map.put("s333", "s333;;0;tastschalter;beleuchtung;instrumente;?;kabinere420;#");
        map.put("9.99.10", "9.99.10;i;0;lampe;stellstrom;zeiger;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w6_ma5", "ln_ln_w6_ma5;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("s235", "s235;i;0;schalter;sifa;pedal;?;kabinere420;#");
        map.put("9.99.11", "9.99.11;i;0;lampe;weichenüberw;zeiger;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w4_pa6", "ln_ln_w4_pa6;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("w238_t", "w238_t;o;0;warntongeber;signum;tief;?;kabinere420;#");
        map.put("9.99.12", "9.99.12;i;0;lampe;schienenstrom;zeiger;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w3_ma6", "ln_ln_w3_ma6;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("w238_h", "w238_h;o;0;warntongeber;signum;hoch;?;kabinere420;#");
        map.put("3.01.01", "3.01.01;o;0;magnet;ws1;magnet;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w6_ma6", "ln_ln_w6_ma6;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l317", "l317;;0;lampe;fernlicht;dienstbeleuchtung;?;kabinere420;#");
        map.put("3.04.01", "3.04.01;o;0;magnet;fssegf;sperrmagnet;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft2a6", "ln_geprueft2a6;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l242b", "l242b;o;0;lampe;zugsicherung;warnung;?;kabinere420;#");
        map.put("3.04.02", "3.04.02;o;0;magnet;fssegf;kuppelstrommagnet;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w2_ma6", "ln_ln_w2_ma6;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l242a", "l242a;o;0;lampe;zugsicherung;halt;?;kabinere420;#");
        map.put("9.93.01", "9.93.01;i;0;;;;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w1_pa6", "ln_ln_w1_pa6;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("cabine.zusi.quittung.gelb", "cabine.zusi.quittung.gelb;o;1;cabinezusi;quittung;grlb;?;kabinere420;#");
        map.put("6.90.01", "6.90.01;i;0;taste;anforderungdurchfahrt;nach_emm;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft1a6", "ln_geprueft1a6;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("cabine.zusi.quittung.rot", "cabine.zusi.quittung.rot;o;1;cabinezusi;quittung;rot;?;kabinere420;#");
        map.put("6.91.02", "6.91.02;i;0;taste;blockfba;nach_zb;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w1_pe4", "ln_ln_w1_pe4;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94vi", "d94vi;o;0;analog-instrument;geschwindigkeitsanzeige;ist;?;kabinere420;#");
        map.put("6.91.01", "6.91.01;i;0;taste;blockfbf;nach_zb;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w3_me5", "ln_ln_w3_me5;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94vi.1", "d94vi.1;o;0;analog-instrument;geschwindigkeitsanzeige;geschwindigkeit;?;kabinere420;#");
        map.put("6.91.03", "6.91.03;i;0;taste;blockrm;nach_zb;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w2_pe2", "ln_ln_w2_pe2;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94vi.2", "d94vi.2;o;0;;;;?;kabinere420;#");
        map.put("6.91.04", "6.91.04;i;0;taste;blockrm;nach_ln;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w1_pe5", "ln_ln_w1_pe5;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94vi.3", "d94vi.3;o;0;;;;?;kabinere420;#");
        map.put("6.91.05", "6.91.05;i;0;taste;blockfba;nach_ln;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w6_me6", "ln_ln_w6_me6;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94vi.4", "d94vi.4;o;0;;;;?;kabinere420;#");
        map.put("6.91.06", "6.91.06;i;0;taste;blockfbf;nach_ln;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w1_pe2", "ln_ln_w1_pe2;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94vi.5", "d94vi.5;o;0;;;;?;kabinere420;#");
        map.put("6.91.07", "6.91.07;i;0;taste;blockblu;alle_richtungen;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w5_pe3", "ln_ln_w5_pe3;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94vi.6", "d94vi.6;o;0;;;;?;kabinere420;#");
        map.put("6.91.08", "6.91.08;i;0;taste;gleis;richtung_emm;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w6_me5", "ln_ln_w6_me5;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94vi.7", "d94vi.7;o;0;;;;?;kabinere420;#");
        map.put("6.91.09", "6.91.09;i;0;taste;wecker;abschalten;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w4_pe6", "ln_ln_w4_pe6;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94vi.8", "d94vi.8;o;0;;;;?;kabinere420;#");
        map.put("6.91.10", "6.91.10;i;0;taste;nottaste;weiche_1;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w1_pe6", "ln_ln_w1_pe6;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94m", "d94m;;0;analoganzeige;lzb;weganzeige;?;kabinere420;#");
        map.put("6.91.11", "6.91.11;i;0;taste;weichen;beleuchtung;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w4_pe5", "ln_ln_w4_pe5;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94u.1", "d94u.1;o;0;;;;?;kabinere420;#");
        map.put("6.91.12", "6.91.12;i;0;taste;zeitschalter;umgehugn;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w3_me6", "ln_ln_w3_me6;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94u.2", "d94u.2;o;0;;;;?;kabinere420;#");
        map.put("6.91.13", "6.91.13;i;0;taste;nal;alle_fahrstrassen;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w3_pe3", "ln_ln_w3_pe3;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94u.3", "d94u.3;o;0;;;;?;kabinere420;#");
        map.put("6.91.14", "6.91.14;i;0;taste;gleis;richtung_zb;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w2_me6", "ln_ln_w2_me6;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94lzb_z5", "d94lzb_z5;;0;ziffernanzeige;lzb;digitalanzeige;?;kabinere420;#");
        map.put("6.91.15", "6.91.15;i;0;taste;siu;alle_fahrstrassen;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w2_me3", "ln_ln_w2_me3;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("d94lzb_z3", "d94lzb_z3;;0;ziffernanzeige;lzb;digitalanzeige;?;kabinere420;#");
        map.put("7.91.01", "7.91.01;i;0;schalterkontakt;ws1;endlage+;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w1_pe3", "ln_ln_w1_pe3;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l94_lzb_r", "l94_lzb_r;;0;lampe;lzb;anzeige ;?;kabinere420;#");
        map.put("7.91.02", "7.91.02;i;0;schalterkontakt;ws1;gedrückt;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w2_me5", "ln_ln_w2_me5;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l94_lzb_gr", "l94_lzb_gr;;0;lampe;lzb;anzeige ;?;kabinere420;#");
        map.put("7.91.04", "7.91.04;i;0;schalterkontakt;ws1;endlage-;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w2_me4", "ln_ln_w2_me4;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l94_lzb_gb", "l94_lzb_gb;;0;lampe;lzb;anzeige ;?;kabinere420;#");
        map.put("8.91.02", "8.91.02;i;0;schalterkontakt;fssegf;endlage_gedrückt;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w3_pe4", "ln_ln_w3_pe4;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l94_lzb_w", "l94_lzb_w;;0;lampe;lzb;anzeige ;?;kabinere420;#");
        map.put("8.91.01", "8.91.01;i;0;schalterkontakt;fssegf;endlage;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w5_me4", "ln_ln_w5_me4;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("a74", "a74;o;0;analog-instrument;spannung;fahrdraht;?;kabinere420;#");
        map.put("8.91.03", "8.91.03;i;0;schalterkontakt;fssegf;10°f;?;stellwerkobermattlangnau;#");	map.put("ln_geprueft1e6", "ln_geprueft1e6;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("a79", "a79;o;0;analog-instrument;strom;i_max;?;kabinere420;#");
        map.put("8.91.04", "8.91.04;i;0;schalterkontakt;fssegf;30°f;?;stellwerkobermattlangnau;#");	map.put("ln_c1_fahrt2", "ln_c1_fahrt2;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("a79.1", "a79.1;o;0;analog-instrument;strom;i_delta;?;kabinere420;#");
        map.put("8.91.05", "8.91.05;i;0;schalterkontakt;fssegf;45°f;?;stellwerkobermattlangnau;#");	map.put("ln_c1_halt", "ln_c1_halt;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("p13c_hb", "p13c_hb;;0;0;0;0;?;kabinere420;#");
        map.put("8.91.06", "8.91.06;i;0;schalterkontakt;fssegf;80°f;?;stellwerkobermattlangnau;#");	map.put("ln_c26_fb2", "ln_c26_fb2;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("p13c_hl", "p13c_hl;;0;0;0;0;?;kabinere420;#");
        map.put("8.91.07", "8.91.07;i;0;schalterkontakt;fssegf;90°f;?;stellwerkobermattlangnau;#");	map.put("ln_c26_fahrt", "ln_c26_fahrt;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("p13c_bz", "p13c_bz;;0;0;0;0;?;kabinere420;#");
        map.put("8.91.19", "8.91.19;i;0;schalterkontakt;fssegf;10°eg;?;stellwerkobermattlangnau;#");	map.put("ln_c26_halt", "ln_c26_halt;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("ao269", "ao269;ia;0;drucksensor;druck;hauptleitung;?;kabinere420;#");
        map.put("8.91.20", "8.91.20;i;0;schalterkontakt;fssegf;30°eg;?;stellwerkobermattlangnau;#");	map.put("ln_c26_fb1", "ln_c26_fb1;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("ao173", "ao173;ia;0;drucksensor;druck;bremszylinder;?;kabinere420;#");
        map.put("8.91.21", "8.91.21;i;0;schalterkontakt;fssegf;45°eg;?;stellwerkobermattlangnau;#");	map.put("ln_e_fb2", "ln_e_fb2;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l281", "l281;o;0;lampe;meldelampe;schleudern;?;kabinere420;#");
        map.put("8.91.22", "8.91.22;i;0;schalterkontakt;fssegf;80°eg;?;stellwerkobermattlangnau;#");	map.put("ln_e_fahrt", "ln_e_fahrt;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l281.1", "l281.1;o;0;taste;schleuderbremse;kabine;?;kabinere420;#");
        map.put("8.91.23", "8.91.23;i;0;schalterkontakt;fssegf;90°eg;?;stellwerkobermattlangnau;#");	map.put("ln_e_halt", "ln_e_halt;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l83", "l83;o;0;lampe;meldelampe;zssheizlampe;?;kabinere420;#");
        map.put("10.99.01", "10.99.01;i;1;kontakt;isolierung;belegt;?;stellwerkobermattlangnau;#");	map.put("ln_e_fb1", "ln_e_fb1;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l175", "l175;o;0;lampe;meldelampe;stoeventi;?;kabinere420;#");
        map.put("10.99.02", "10.99.02;;1;;;;?;stellwerkobermattlangnau;#");	map.put("ln_ln_w1_me1", "ln_ln_w1_me1;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l163", "l163;o;0;lampe;meldelampe;stufensch;?;kabinere420;#");
        map.put("10.99.04", "10.99.04;i;1;kontakt;isolierung;belegt;?;stellwerkobermattlangnau;#");	map.put("zb_c_fahrt", "zb_c_fahrt;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l181", "l181;o;0;lampe;meldelampe;abf;?;kabinere420;#");
        map.put("10.99.05", "10.99.05;;1;;;;?;stellwerkobermattlangnau;#");	map.put("zb_geprueft1a2", "zb_geprueft1a2;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l182.3", "l182.3;o;0;lampe;meldelampe;tür_l;?;kabinere420;#");
        map.put("10.99.06", "10.99.06;;1;;;;?;stellwerkobermattlangnau;#");	map.put("zb_emm_grundstlg", "zb_emm_grundstlg;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l185", "l185;o;0;lampe;meldelampe;tür_offen;?;kabinere420;#");
        map.put("10.99.07", "10.99.07;i;1;kontakt;isolierung;belegt;?;stellwerkobermattlangnau;#");	map.put("zb_cd_belegt", "zb_cd_belegt;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l182.4", "l182.4;o;0;lampe;meldelampe;tür_r;?;kabinere420;#");
        map.put("10.99.08", "10.99.08;i;1;kontakt;isolierung;belegt;?;stellwerkobermattlangnau;#");	map.put("zb_zb_w2_ma1", "zb_zb_w2_ma1;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l242.2", "l242.2;o;0;lampe;meldelampe;m-taste;?;kabinere420;#");
        map.put("10.99.09", "10.99.09;i;1;kontakt;isolierung;freigabe;?;stellwerkobermattlangnau;#");	map.put("iltis_ln_1_834", "iltis_ln_1_834;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l318a", "l318a;;0;lampe;dienstbel;weiss;?;kabinere420;#");
        map.put("10.99.10", "10.99.10;i;1;kontakt;isolierung;freigabe;?;stellwerkobermattlangnau;#");	map.put("iltis_ln_2_834", "iltis_ln_2_834;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l318b", "l318b;;0;lampe;dienstbel;warnsignal;?;kabinere420;#");
        map.put("11.99.01", "11.99.01;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_ln_5_834", "iltis_ln_5_834;os;;;;;?;petrinetz-obermattlangnau;#");		map.put("l325.2", "l325.2;;0;lampe;fst;fahrplan;?;kabinere420;#");
        map.put("11.99.02", "11.99.02;;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_anfordern_vln", "iltis_anfordern_vln;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("11.99.03", "11.99.03;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_festgehalten_vln", "iltis_festgehalten_vln;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("11.99.04", "11.99.04;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_rueckmelden_ln_om", "iltis_rueckmelden_ln_om;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("11.99.05", "11.99.05;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_anfordern_vzb", "iltis_anfordern_vzb;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("11.99.06", "11.99.06;;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_freigegeben_vln", "iltis_freigegeben_vln;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("11.99.07", "11.99.07;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_freigeben_vln", "iltis_freigeben_vln;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("11.99.08", "11.99.08;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_festhalten_vln", "iltis_festhalten_vln;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("9.99.13", "9.99.13;;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_freigeben_vzb", "iltis_freigeben_vzb;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("9.99.14", "9.99.14;;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_festhalten_vzb", "iltis_festhalten_vzb;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("9.99.15", "9.99.15;;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_freigegeben_vzb", "iltis_freigegeben_vzb;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("11.99.09", "11.99.09;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_festgehalten_v_zb", "iltis_festgehalten_v_zb;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("11.99.10", "11.99.10;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_p230", "iltis_p230;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("9.99.01", "9.99.01;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_rm_moeglich2", "iltis_rm_moeglich2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("9.99.02", "9.99.02;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_rm_ln_om", "iltis_rm_ln_om;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("9.99.03", "9.99.03;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_p130", "iltis_p130;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("6.99.01", "6.99.01;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_rm_moeglich1", "iltis_rm_moeglich1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("6.99.02", "6.99.02;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_rm_zb_om", "iltis_rm_zb_om;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("6.99.03", "6.99.03;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iltis_rueckmelden_zb_om", "iltis_rueckmelden_zb_om;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("12.99.01", "12.99.01;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iso_ef_belegt", "iso_ef_belegt;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("12.99.02", "12.99.02;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("iso_ef_zug_einfahren", "iso_ef_zug_einfahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("12.99.03", "12.99.03;;1;;;;?;stellwerkobermattlangnau;#");	map.put("iso_ef_zug_ausfahren", "iso_ef_zug_ausfahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("12.99.04", "12.99.04;;1;;;;?;stellwerkobermattlangnau;#");	map.put("iso_ef_frei", "iso_ef_frei;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.01", "90.99.01;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_om_ln_1", "bl_om_ln_1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.02", "90.99.02;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_om_ln_grundstlg_n", "bl_om_ln_grundstlg_n;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.03", "90.99.03;;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_om_ln_3", "bl_om_ln_3;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.04", "90.99.04;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_om_ln_vorgebl_v", "bl_om_ln_vorgebl_v;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.05", "90.99.05;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_om_ln_belegt_n", "bl_om_ln_belegt_n;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.06", "90.99.06;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_om_ln_grundstlg_v", "bl_om_ln_grundstlg_v;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.07", "90.99.07;;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_om_ln_2", "bl_om_ln_2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.08", "90.99.08;;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_om_ln_vorgebl_n", "bl_om_ln_vorgebl_n;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.09", "90.99.09;;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_om_ln_belegt_v", "bl_om_ln_belegt_v;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.10", "90.99.10;;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_om_ln_rmm_nln", "bl_om_ln_rmm_nln;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.11", "90.99.11;;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_zb_om_vorgebl_n", "bl_zb_om_vorgebl_n;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.12", "90.99.12;;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_zb_om_belegt_v", "bl_zb_om_belegt_v;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.13", "90.99.13;;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_zb_om_vorgebl_v", "bl_zb_om_vorgebl_v;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.14", "90.99.14;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_zb_om_grundstlg_v", "bl_zb_om_grundstlg_v;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.15", "90.99.15;i;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_zb_om_grundstlg_n", "bl_zb_om_grundstlg_n;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.16", "90.99.16;;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_zb_om_belegt_n", "bl_zb_om_belegt_n;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.17", "90.99.17;;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_zb_om_1", "bl_zb_om_1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.18", "90.99.18;;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_zb_om_2", "bl_zb_om_2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("90.99.19", "90.99.19;;1;;;;?;stellwerkobermattlangnau;#");	map.put("bl_zb_om_3", "bl_zb_om_3;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("bl_zb_om_rmm_nzb", "bl_zb_om_rmm_nzb;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("stw_fss_sperrm_ein", "stw_fss_sperrm_ein;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("stw_fss_sperrm_aus", "stw_fss_sperrm_aus;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("stw_fss_kuppelm_aus", "stw_fss_kuppelm_aus;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("stw_fss_kuppelm_ein", "stw_fss_kuppelm_ein;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("stw_ws_sperrm_aus", "stw_ws_sperrm_aus;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("stw_ws_sperrm_ein", "stw_ws_sperrm_ein;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("stw_p10", "stw_p10;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("stw_p11", "stw_p11;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fe_p1", "fstr_fe_p1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fe_aufgeloest", "fstr_fe_aufgeloest;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fe_p2b", "fstr_fe_p2b;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fe_f_fahrt1", "fstr_fe_f_fahrt1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fe_zug_eingefahren", "fstr_fe_zug_eingefahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fe_f_halt", "fstr_fe_f_halt;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fe_verschlossen", "fstr_fe_verschlossen;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fe_geprueft", "fstr_fe_geprueft;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fe_stoerung_f", "fstr_fe_stoerung_f;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fe_p2", "fstr_fe_p2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_gf_aufgeloest", "fstr_gf_aufgeloest;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_gf_zug_eingefahren", "fstr_gf_zug_eingefahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_gf_g_fahrt3", "fstr_gf_g_fahrt3;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_gf_g_halt", "fstr_gf_g_halt;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_gf_verschlossen", "fstr_gf_verschlossen;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_gf_geprueft1", "fstr_gf_geprueft1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_gf_stoerung_g", "fstr_gf_stoerung_g;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_gf_geprueft2", "fstr_gf_geprueft2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_gf_p4", "fstr_gf_p4;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fg_p1", "fstr_fg_p1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fg_aufgeloest", "fstr_fg_aufgeloest;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fg_p2", "fstr_fg_p2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fg_f_fahrt3", "fstr_fg_f_fahrt3;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fg_zug_eingefahren", "fstr_fg_zug_eingefahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fg_f_halt", "fstr_fg_f_halt;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fg_verschlossen", "fstr_fg_verschlossen;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fg_geprueft1", "fstr_fg_geprueft1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fg_stoerung_f", "fstr_fg_stoerung_f;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fg_geprueft2", "fstr_fg_geprueft2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_fg_geprueft0", "fstr_fg_geprueft0;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_1_zug_ausfahren", "iso_1_zug_ausfahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_1_belegt", "iso_1_belegt;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_1_zug_einfahren", "iso_1_zug_einfahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_1_frei", "iso_1_frei;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_gf_zug_ausfahren", "iso_gf_zug_ausfahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_gf_belegt", "iso_gf_belegt;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_gf_zug_einfahren", "iso_gf_zug_einfahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_gf_frei", "iso_gf_frei;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_egf_zug_ausfahren", "iso_egf_zug_ausfahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_egf_belegt", "iso_egf_belegt;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_egf_zug_einfahren", "iso_egf_zug_einfahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_egf_frei", "iso_egf_frei;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_cd_frei", "iso_cd_frei;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_cd_belegt", "iso_cd_belegt;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_cd_zug_einfahren", "iso_cd_zug_einfahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iso_cd_zug_ausfahren", "iso_cd_zug_ausfahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_f_vs_stoer", "lampen_1_f_vs_stoer;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_f_gruenfb1", "lampen_1_f_gruenfb1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_grundstlg", "emm_emm_grundstlg;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft1a1", "emm_geprueft1a1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w7_ma1", "emm_emm_w7_ma1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w10_pa1", "emm_emm_w10_pa1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft2a1", "emm_geprueft2a1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_om_e_fahrt", "emm_om_e_fahrt;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft1a2", "emm_geprueft1a2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w10_pa2", "emm_emm_w10_pa2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft2a2", "emm_geprueft2a2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w7_pa2", "emm_emm_w7_pa2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft1a3", "emm_geprueft1a3;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w10_ma3", "emm_emm_w10_ma3;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft2a3", "emm_geprueft2a3;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w9_pa3", "emm_emm_w9_pa3;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft1a4", "emm_geprueft1a4;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w9_ma4", "emm_emm_w9_ma4;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft2a4", "emm_geprueft2a4;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w8_pa4", "emm_emm_w8_pa4;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft1a5", "emm_geprueft1a5;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w9_ma5", "emm_emm_w9_ma5;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft2a5", "emm_geprueft2a5;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w8_ma5", "emm_emm_w8_ma5;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft1e1", "emm_geprueft1e1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w10_pe1", "emm_emm_w10_pe1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w7_me1", "emm_emm_w7_me1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft1e2", "emm_geprueft1e2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w10_pe2", "emm_emm_w10_pe2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w7_pe2", "emm_emm_w7_pe2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft1e3", "emm_geprueft1e3;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w10_me3", "emm_emm_w10_me3;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w9_pe3", "emm_emm_w9_pe3;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft1e4", "emm_geprueft1e4;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w9_me4", "emm_emm_w9_me4;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w8_pe4", "emm_emm_w8_pe4;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_geprueft1e5", "emm_geprueft1e5;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w9_me5", "emm_emm_w9_me5;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w8_me5", "emm_emm_w8_me5;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w10_ma4", "emm_emm_w10_ma4;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w10_ma5", "emm_emm_w10_ma5;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w10_me4", "emm_emm_w10_me4;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_emm_w10_me5", "emm_emm_w10_me5;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("emm_c_fb2", "emm_c_fb2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_g_vs_stoer", "lampen_1_g_vs_stoer;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_bl_vln_rot", "lampen_1_bl_vln_rot;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_bl_vln_weiss", "lampen_1_bl_vln_weiss;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_bl_nln_weiss", "lampen_1_bl_nln_weiss;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_bl_nln_rot", "lampen_1_bl_nln_rot;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_fstr_ef", "lampen_1_fstr_ef;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_fstr_gf", "lampen_1_fstr_gf;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_bl_nzb_rot", "lampen_1_bl_nzb_rot;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_bl_nzb_weiss", "lampen_1_bl_nzb_weiss;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_bl_vzb_weiss", "lampen_1_bl_vzb_weiss;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_bl_vzb_rot", "lampen_1_bl_vzb_rot;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_fbv_vln", "lampen_1_fbv_vln;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_stoer_wecker", "lampen_1_stoer_wecker;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_ws1_freig", "lampen_1_ws1_freig;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_ws1_ueberw", "lampen_1_ws1_ueberw;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_2_weiche", "lampen_2_weiche;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_2_block", "lampen_2_block;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_2_signal", "lampen_2_signal;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_f_rot", "lampen_1_f_rot;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p41", "lampen_p41;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p48", "lampen_p48;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p49", "lampen_p49;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_1_fbv_vzb", "lampen_1_fbv_vzb;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p4", "lampen_p4;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p6", "lampen_p6;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p8", "lampen_p8;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p112", "lampen_p112;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p15", "lampen_p15;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p16", "lampen_p16;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p17", "lampen_p17;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p20", "lampen_p20;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p23", "lampen_p23;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p26", "lampen_p26;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p30", "lampen_p30;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p32", "lampen_p32;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p33", "lampen_p33;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p34", "lampen_p34;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p35", "lampen_p35;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p38", "lampen_p38;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p1", "lampen_p1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p12", "lampen_p12;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p13", "lampen_p13;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p117", "lampen_p117;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p18", "lampen_p18;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p21", "lampen_p21;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p22", "lampen_p22;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p40", "lampen_p40;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p27", "lampen_p27;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p39", "lampen_p39;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_p135", "lampen_p135;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_iso_cd_aus", "lampen_iso_cd_aus;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_iso_cd_ein", "lampen_iso_cd_ein;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_iso_1_aus", "lampen_iso_1_aus;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_iso_1_ein", "lampen_iso_1_ein;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_iso_egf_aus", "lampen_iso_egf_aus;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_iso_egf_ein", "lampen_iso_egf_ein;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_iso_ef_aus", "lampen_iso_ef_aus;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("lampen_iso_ef_ein", "lampen_iso_ef_ein;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_6_fba_nzb", "kontakte_6_fba_nzb;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_6_fbf_nzb", "kontakte_6_fbf_nzb;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_6_rm_nzb", "kontakte_6_rm_nzb;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_6_rm_nln", "kontakte_6_rm_nln;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_6_fba_nln", "kontakte_6_fba_nln;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_6_fbf_nln", "kontakte_6_fbf_nln;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_6_blu_eg", "kontakte_6_blu_eg;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_6_gleist_emm", "kontakte_6_gleist_emm;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_6_nt_w1", "kontakte_6_nt_w1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_6_nal", "kontakte_6_nal;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_6_gleist_zb", "kontakte_6_gleist_zb;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_6_isu_sign", "kontakte_6_isu_sign;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_7_ws1_plus", "kontakte_7_ws1_plus;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_7_ws1_minus", "kontakte_7_ws1_minus;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_7_ws1_1", "kontakte_7_ws1_1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_8_fss_10eg", "kontakte_8_fss_10eg;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_8_fss_30eg", "kontakte_8_fss_30eg;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_8_fss_45eg", "kontakte_8_fss_45eg;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_8_fss_90eg", "kontakte_8_fss_90eg;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_8_fss_10f", "kontakte_8_fss_10f;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_8_fss_30f", "kontakte_8_fss_30f;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_8_fss_45f", "kontakte_8_fss_45f;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("kontakte_8_fss_90f", "kontakte_8_fss_90f;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("ext_vb_ueberw_w1_plus", "ext_vb_ueberw_w1_plus;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("ext_vb_ueberw_w1_minus", "ext_vb_ueberw_w1_minus;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("ext_vb_f_vs_lampe_warn_def", "ext_vb_f_vs_lampe_warn_def;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("ext_vb_f_vs_lampe_fahrt_def", "ext_vb_f_vs_lampe_fahrt_def;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("ext_vb_g_vs_lampe_warn_def", "ext_vb_g_vs_lampe_warn_def;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("ext_vb_g_vs_lampe_fahrt_def", "ext_vb_g_vs_lampe_fahrt_def;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_geprueft1e2", "zb_geprueft1e2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_zb_w2_me1", "zb_zb_w2_me1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_d_fahrt", "zb_d_fahrt;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_zb_w2_pe2", "zb_zb_w2_pe2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_geprueft1a1", "zb_geprueft1a1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_zb_w2_pa2", "zb_zb_w2_pa2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_d_halt", "zb_d_halt;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_geprueft2a2", "zb_geprueft2a2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_geprueft1e1", "zb_geprueft1e1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_c_halt", "zb_c_halt;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_geprueft2a1", "zb_geprueft2a1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_zb_w1_pe2", "zb_zb_w1_pe2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_zb_w1_me1", "zb_zb_w1_me1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_zb_w1_pa2", "zb_zb_w1_pa2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_zb_w1_ma1", "zb_zb_w1_ma1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_c_fb1", "zb_c_fb1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_c_fb2", "zb_c_fb2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_d_fb1", "zb_d_fb1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("zb_d_fb2", "zb_d_fb2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_emm_1_833", "iltis_emm_1_833;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_emm_2_833", "iltis_emm_2_833;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_emm_3_833", "iltis_emm_3_833;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_emm_4_833", "iltis_emm_4_833;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_emm_5_833", "iltis_emm_5_833;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_emm_833_1", "iltis_emm_833_1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_emm_833_2", "iltis_emm_833_2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_emm_833_3", "iltis_emm_833_3;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_emm_833_4", "iltis_emm_833_4;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_emm_833_5", "iltis_emm_833_5;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_zb_1_138", "iltis_zb_1_138;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_zb_2_138", "iltis_zb_2_138;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_zb_138_1", "iltis_zb_138_1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_zb_138_2", "iltis_zb_138_2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_ln_834_1", "iltis_ln_834_1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_ln_834_2", "iltis_ln_834_2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_ln_834_3", "iltis_ln_834_3;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_ln_834_4", "iltis_ln_834_4;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_ln_834_5", "iltis_ln_834_5;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_ln_834_6", "iltis_ln_834_6;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_ln_6_834", "iltis_ln_6_834;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_ln_4_834", "iltis_ln_4_834;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("iltis_ln_3_834", "iltis_ln_3_834;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_ef_e_halt", "fstr_ef_e_halt;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_ef_e_fahrt1", "fstr_ef_e_fahrt1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_ef_aufgeloest", "fstr_ef_aufgeloest;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_ef_p1", "fstr_ef_p1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_ef_p2", "fstr_ef_p2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_ef_zug_eingefahren", "fstr_ef_zug_eingefahren;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_ef_geprueft1", "fstr_ef_geprueft1;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_ef_geprueft2", "fstr_ef_geprueft2;os;;;;;?;petrinetz-obermattlangnau;#");
        map.put("fstr_ef_p6", "fstr_ef_p6;os;;;;;?;petrinetz-obermattlangnau;#");
    }
}
